<<<<<<< HEAD
title: Cayman theme
description: Cayman is a clean, responsive theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
=======
theme: jekyll-theme-cayman
description: Add StackEdit to any website
show_downloads: true
>>>>>>> upstream/master
